name: Production Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  release:
    name: "Update release branch"
    uses: humanmade/hm-github-actions/.github/workflows/build-and-release-node.yml@30453184705435637cae557f8fb4578e6a395657
    with:
      node_version: 22
      source_branch: main
      release_branch: release
      built_asset_paths: build
