name: Develop Release

on:
  push:
    branches:
      - add-gh-actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  release-develop:
    name: "Update release-develop branch"
    runs-on: ubuntu-latest
    steps:
      - uses: humanmade/hm-github-actions/.github/workflows/build-and-release-node-basic.yml@e9d83e785d128a9b49b0e85f02643dae73574900
        with:
          source_branch: add-gh-actions
          release_branch: release-develop
          built_asset_paths: build
          build_script: |
            npm ci
            npm run build
